from __future__ import annotations

import hashlib
from dataclasses import dataclass
from datetime import UTC, datetime
from types import MappingProxyType
from typing import Any, Mapping
from zoneinfo import ZoneInfo

import httpx

from app.core.config import settings
from app.core.team_identity import stable_team_name_key

MAX_PAYLOAD_BYTES = 4 * 1024 * 1024


class OpenFootballError(RuntimeError):
    """Base error for the public-domain OpenFootball JSON source."""


class OpenFootballDownloadError(OpenFootballError):
    """Raised when the official GitHub-hosted dataset cannot be downloaded."""


class OpenFootballFormatError(OpenFootballError):
    """Raised when a dataset violates the expected JSON contract."""


@dataclass(frozen=True, slots=True)
class OpenFootballLeague:
    league_id: int
    slug: str
    country: str
    timezone: str


OPENFOOTBALL_LEAGUES: Mapping[int, OpenFootballLeague] = MappingProxyType(
    {
        197: OpenFootballLeague(
            league_id=197,
            slug="gr.1",
            country="Greece",
            timezone="Europe/Athens",
        )
    }
)


def _stable_negative_id(namespace: str, natural_key: str) -> int:
    digest = hashlib.blake2b(
        f"{namespace}:{natural_key}".encode("utf-8"), digest_size=8
    ).digest()
    identifier = int.from_bytes(digest, byteorder="big") & ((1 << 63) - 1)
    return -(identifier or 1)


def _score_pair(value: object) -> tuple[int, int] | None:
    if (
        not isinstance(value, list)
        or len(value) != 2
        or any(
            isinstance(score, bool) or not isinstance(score, int) or score < 0
            for score in value
        )
    ):
        return None
    return value[0], value[1]


class OpenFootballJSONClient:
    """Download and validate CC0 match results generated by OpenFootball."""

    def __init__(
        self,
        *,
        base_url: str | None = None,
        timeout_seconds: float | None = None,
        transport: httpx.AsyncBaseTransport | None = None,
        enabled: bool | None = None,
    ) -> None:
        self.base_url = (base_url or settings.OPENFOOTBALL_BASE_URL).rstrip("/")
        self.timeout_seconds = timeout_seconds or settings.OPENFOOTBALL_TIMEOUT_SECONDS
        self.transport = transport
        self.enabled = settings.OPENFOOTBALL_ENABLED if enabled is None else enabled

    @property
    def supported_league_ids(self) -> frozenset[int]:
        return frozenset(OPENFOOTBALL_LEAGUES)

    async def get_completed_fixtures(
        self, league_id: int, season: int
    ) -> list[dict[str, Any]]:
        if not self.enabled:
            return []
        league = OPENFOOTBALL_LEAGUES.get(league_id)
        if league is None:
            raise ValueError(f"Unsupported OpenFootball league_id: {league_id}")
        if season < 2000 or season > datetime.now(UTC).year + 1:
            raise ValueError(f"Invalid season: {season}")

        season_path = f"{season}-{(season + 1) % 100:02d}"
        payload = await self._download(f"{season_path}/{league.slug}.json")
        return self._parse(payload, league=league, season=season)

    async def _download(self, path: str) -> object:
        try:
            async with httpx.AsyncClient(
                timeout=self.timeout_seconds,
                follow_redirects=False,
                transport=self.transport,
                headers={"User-Agent": "BetAIPlatform/1.0 openfootball-importer"},
            ) as client:
                response = await client.get(f"{self.base_url}/{path}")
                response.raise_for_status()
        except httpx.HTTPError as exc:
            raise OpenFootballDownloadError(
                f"OpenFootball dataset could not be downloaded: {path}"
            ) from exc
        if len(response.content) > MAX_PAYLOAD_BYTES:
            raise OpenFootballFormatError("OpenFootball dataset is too large")
        try:
            return response.json()
        except ValueError as exc:
            raise OpenFootballFormatError(
                "OpenFootball dataset is not valid JSON"
            ) from exc

    @staticmethod
    def _parse(
        payload: object,
        *,
        league: OpenFootballLeague,
        season: int,
    ) -> list[dict[str, Any]]:
        if not isinstance(payload, dict) or not isinstance(
            payload.get("matches"), list
        ):
            raise OpenFootballFormatError("OpenFootball matches must be a list")

        fixtures: list[dict[str, Any]] = []
        natural_keys: set[str] = set()
        for index, raw in enumerate(payload["matches"], start=1):
            if not isinstance(raw, dict):
                raise OpenFootballFormatError(f"Invalid match row {index}")
            home = str(raw.get("team1") or "").strip()
            away = str(raw.get("team2") or "").strip()
            date_value = str(raw.get("date") or "").strip()
            time_value = str(raw.get("time") or "12:00").strip()
            score = raw.get("score")
            full_time = score.get("ft") if isinstance(score, dict) else None

            # Published schedules legitimately contain future, unscored matches.
            if full_time is None:
                continue
            if not home or not away or home == away or not date_value:
                raise OpenFootballFormatError(f"Invalid match identity at row {index}")
            full_time_pair = _score_pair(full_time)
            if full_time_pair is None:
                raise OpenFootballFormatError(f"Invalid full-time score at row {index}")
            try:
                local_kickoff = datetime.fromisoformat(
                    f"{date_value}T{time_value}"
                ).replace(tzinfo=ZoneInfo(league.timezone))
            except ValueError as exc:
                raise OpenFootballFormatError(
                    f"Invalid match date at row {index}"
                ) from exc

            home_key = f"{league.country}:{stable_team_name_key(home)}"
            away_key = f"{league.country}:{stable_team_name_key(away)}"
            kickoff = local_kickoff.astimezone(UTC)
            natural_key = f"{league.league_id}:{season}:{kickoff.isoformat()}:{home_key}:{away_key}"
            if natural_key in natural_keys:
                raise OpenFootballFormatError(f"Duplicate match at row {index}")
            natural_keys.add(natural_key)

            home_score, away_score = full_time_pair
            half_time_pair = _score_pair(
                score.get("ht") if isinstance(score, dict) else None
            )
            fixtures.append(
                {
                    "fixture_id": _stable_negative_id(
                        "openfootball-fixture", natural_key
                    ),
                    "league_id": league.league_id,
                    "season": season,
                    "kickoff": kickoff,
                    "home_team_id": _stable_negative_id("openfootball-team", home_key),
                    "away_team_id": _stable_negative_id("openfootball-team", away_key),
                    "home_team": home[:100],
                    "away_team": away[:100],
                    "home_goals": home_score,
                    "away_goals": away_score,
                    "half_time_home_goals": (
                        half_time_pair[0] if half_time_pair else None
                    ),
                    "half_time_away_goals": (
                        half_time_pair[1] if half_time_pair else None
                    ),
                    "home_starting_xi": None,
                    "away_starting_xi": None,
                    "actual_result": (
                        "HOME_WIN"
                        if home_score > away_score
                        else "AWAY_WIN" if away_score > home_score else "DRAW"
                    ),
                    "status": "FT",
                    "data_source": "openfootball_json",
                }
            )
        return fixtures
